# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=511)),
                ('image', models.ImageField(height_field=512, upload_to='', width_field=512)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisedQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classroom_type', models.IntegerField(choices=[(-1, 'N/A'), (0, 'Other'), (1, 'Small lecture hall'), (2, 'Small laboratory'), (3, 'Big lecture hall'), (4, "Teachers' room")], default=-1)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=100, unique_for_year='date')),
            ],
        ),
        migrations.CreateModel(
            name='KlimrUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('djuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assignments', models.ManyToManyField(to='klimr_main.Assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Classroom')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, 'Autograph'), (1, 'Assignment'), (2, 'Question')])),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('assignments', models.ManyToManyField(blank=True, to='klimr_main.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateField()),
                ('test_week_on', models.DateField(unique_for_year='start_on')),
                ('test_week_end_on', models.DateField(unique_for_year='start_on')),
                ('session_on', models.DateField(unique_for_year='start_on')),
                ('session_end_on', models.DateField(unique_for_year='start_on')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('first_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Semester')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Person')),
            ],
        ),
        migrations.AddField(
            model_name='queuerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Student'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.QueueRecord'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='lessontiming',
            unique_together=set([('start', 'end')]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_time', to='klimr_main.LessonTiming'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(to='klimr_main.Subgroup'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_time', to='klimr_main.LessonTiming'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Teacher'),
        ),
        migrations.AddField(
            model_name='klimruser',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='klimr_main.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='first_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Semester'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(to='klimr_main.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Department'),
        ),
        migrations.AddField(
            model_name='completedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Discipline'),
        ),
        migrations.AddField(
            model_name='advisedqueue',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klimr_main.QueueRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='advisedqueue',
            unique_together=set([('record', 'rank')]),
        ),
    ]
