# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuerecord',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Lesson'),
            preserve_default=False,
        ),
    ]
