# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0003_auto_20170417_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='klimr_main.Person'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='klimr_main.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set([('person', 'department')]),
        ),
    ]
