# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0004_auto_20170417_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expelled',
            field=models.BooleanField(default=False),
        ),
    ]
