# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0005_student_expelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSemesterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='first_semester',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expelled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='student',
            name='expelled_in',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='subgroups',
            field=models.ManyToManyField(to='klimr_main.Subgroup'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='disciplines',
            field=models.ManyToManyField(to='klimr_main.Discipline'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='teachers',
            field=models.ManyToManyField(to='klimr_main.Teacher'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.GroupSemesterState'),
        ),
        migrations.AddField(
            model_name='groupsemesterstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='klimr_main.Group'),
        ),
        migrations.AddField(
            model_name='groupsemesterstate',
            name='praepostor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Student'),
        ),
        migrations.AddField(
            model_name='groupsemesterstate',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimr_main.Semester'),
        ),
    ]
