# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0006_auto_20170419_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsemesterstate',
            options={'get_latest_by': 'semester__start_on'},
        ),
        migrations.AddField(
            model_name='subgroup',
            name='primary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
