# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0010_auto_20170526_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, to='klimr_main.Assignment'),
        ),
    ]
