# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimr_main', '0011_auto_20170526_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time__start']},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='klimr_main.Assignment'),
        ),
    ]
